import { RecommendationRules } from "./types";

export const recommendationRules: RecommendationRules = {
  "apple:ripe": "Best for immediate consumption. Rich in fiber and good for health.",
  "apple:unripe": "Keep for a few more days for better sweetness.",
  "banana:ripe": "Ready to eat. Rich in potassium and energy.",
  "banana:unripe": "Keep at room temperature for 2-3 days before eating.",
  "banana:overripe": "Best for smoothies, shakes, or banana cake.",
  "orange:ripe": "Excellent source of Vitamin C and hydration.",
  "orange:unripe": "May taste sour. Allow more ripening time.",
  "mango:ripe": "Sweet and juicy. Best served chilled.",
  "mango:unripe": "Can be used for pickles or allow more ripening.",
  "mango:overripe": "Good for juices, milkshakes, and desserts.",
  "guava:ripe": "Crunchy and rich in Vitamin C.",
  "papaya:ripe": "Good for digestion and healthy eating.",
  "papaya:overripe": "Can be blended into smoothies or desserts.",
  "pineapple:ripe": "Sweet tropical fruit perfect for juice and desserts.",
  "watermelon:ripe": "Best served cold for maximum refreshment.",
  "muskmelon:ripe": "Cooling summer fruit with high water content.",
  "pomegranate:ripe": "Rich in antioxidants and good for blood health.",
  "grapes:ripe": "Sweet and juicy. Great for snacks and juice.",
  "pear:ripe": "Soft and juicy. Best consumed fresh.",
  "kiwi:ripe": "Tangy fruit rich in Vitamin C.",
  "strawberry:ripe": "Perfect for desserts, shakes, and ice cream.",
  "blueberry:ripe": "Rich in antioxidants and brain healthy nutrients.",
  "cherry:ripe": "Sweet fruit ideal for desserts and cakes.",
  "peach:ripe": "Soft juicy fruit best eaten fresh.",
  "plum:ripe": "Sweet tart fruit rich in vitamins.",
  "apricot:ripe": "Nutritious fruit suitable for dry fruit products.",
  "avocado:ripe": "Perfect for salads, sandwiches, and guacamole.",
  "lychee:ripe": "Sweet juicy tropical fruit best served chilled.",
  "jackfruit:ripe": "Sweet tropical fruit rich in carbohydrates.",
  "coconut:ripe": "Useful for coconut water, desserts, and cooking.",
  "sapodilla:ripe": "Very sweet fruit rich in natural sugars.",
  "custard apple:ripe": "Creamy sweet fruit best eaten fresh.",
  "jamun:ripe": "Beneficial for diabetic-friendly diets.",
  "amla:ripe": "Extremely rich in Vitamin C and immunity boosting.",
  "wood apple:ripe": "Traditional fruit useful for digestion.",
  "bael:ripe": "Cooling fruit often used in summer drinks.",
  "star fruit:ripe": "Sweet sour fruit suitable for juices and salads.",
  "mulberry:ripe": "Nutritious berry rich in antioxidants.",
  "indian blackberry:ripe": "Juicy berry fruit suitable for desserts and jams.",
  "tamarind:ripe": "Popular sour fruit used in cooking and chutneys.",
  "ber:ripe": "Crunchy sweet fruit ideal for snacks.",
  "sugarcane:ripe": "Excellent for fresh sugarcane juice.",
  "dragon fruit:ripe": "Exotic fruit rich in antioxidants and hydration.",
  "passion fruit:ripe": "Aromatic fruit suitable for juices and desserts.",
  "fig:ripe": "Fiber-rich fruit beneficial for digestion.",
  "dates:ripe": "Energy-rich fruit commonly eaten during fasting.",
  "rambutan:ripe": "Sweet exotic fruit with juicy flesh.",
  "longan:ripe": "Refreshing tropical fruit with sweet flavor.",
  "mangosteen:ripe": "Known as the queen of fruits with sweet tangy taste.",
  "pomelo:ripe": "Large citrus fruit rich in Vitamin C.",
  "sweet lime:ripe": "Refreshing juice fruit suitable for summer.",
  "mandarin:ripe": "Easy-to-peel citrus fruit with sweet flavor.",
  "cranberry:ripe": "Commonly used in juices and healthy drinks.",
  "blackberry:ripe": "Dark berry rich in antioxidants.",
  "raspberry:ripe": "Soft berry fruit suitable for desserts.",
  "gooseberry:ripe": "Nutritious sour fruit rich in vitamins.",
  "tomato:ripe": "Useful for salads, sauces, and cooking."
};
